### 18. NUMPY − MATRIX LIBRARY

NumPy-யில் உள்ள **matrix library** என்பது matrix-களை உருவாக்கவும்,
நிர்வகிக்கவும் உதவும் functions-களை கொண்டுள்ளது. NumPy.matlib functions-ஐ
பயன்படுத்தி, நீங்கள் matrix operations-ஐ memory-efficient-ஆகவும்
computationally fast-ஆகவும் செயல்படுத்த முடியும். இது scientific computing
மற்றும் linear algebra operations-ஐ எளிமையாக செய்கிறது.

#### 18.1. matlib.empty()

**matlib.empty()** function-ஐ பயன்படுத்தி, uninitialized values கொண்ட ஒரு
matrix-ஐ உருவாக்கலாம். Uninitialized matrix என்பது memory-யில் உள்ள பயனற்ற
values-ஐ பயன்படுத்தி matrix-ஐ உருவாக்கும், இதனால் memory allocation மிக
வேகமாக இருக்கும்.

**Example:**

``` python
import numpy.matlib as matlib

# Empty matrix உருவாக்கல்
empty_matrix = matlib.empty((2, 3))
print("Empty matrix:\n", empty_matrix)
```

**Output:**

    Empty matrix:
     [[4.66651921e-310 0.00000000e+000 2.05833592e-312]
     [6.79038654e-313 2.14321575e-312 2.27053550e-312]]

#### விளக்கம்:

-   **matlib.empty()** function-ஐ பயன்படுத்தி, 2 rows மற்றும் 3 columns கொண்ட
    uninitialized matrix-ஐ உருவாக்கியுள்ளோம்.
-   Uninitialized matrix values என்பது random memory values ஆகும், ஏனெனில்
    values-ஐ initialize செய்யாமல் memory-யில் allocate செய்யப்படுகிறது.
-   இந்த method-ஐ data initialization தேவையில்லாத computation-ல், மிக
    வேகமாக memory-யை allocate செய்ய பயன்படுத்தலாம்.

#### எப்போது **matlib.empty()** பயன்படுத்த வேண்டும்?

-   **Performance Optimization**: Memory-யை வேகமாக allocate செய்ய வேண்டிய
    இடத்தில், ஆனால் values-ஐ பின்னர் initialize செய்யும் data structures-ல்.
-   **Data Allocation**: Data-ஐ அடிப்படையாக பயன்படுத்தாமல் placeholder ஆக
    memory-யில் data structure உருவாக்கும்போது.

#### 18.2. numpy.matlib.zeros()

**matlib.zeros()** function-ஐ பயன்படுத்தி, எல்லா elements-னும் zeros ஆக உள்ள
ஒரு matrix-ஐ உருவாக்கலாம். இது scientific calculations மற்றும் numerical
computations-ஐ நேரடியாக initialize செய்ய உதவும், ஏனெனில் zeros கொண்ட
matrix-கள் இடம் பிடிக்கும் computation-ஐ எளிமையாக மாற்றுகின்றன.

**Example:**

``` python
# Zeros matrix உருவாக்கல்
zeros_matrix = matlib.zeros((3, 3))
print("Zeros matrix:\n", zeros_matrix)
```

**Output:**

    Zeros matrix:
     [[0. 0. 0.]
     [0. 0. 0.]
     [0. 0. 0.]]

#### விளக்கம்:

-   **matlib.zeros()** function-ஐ பயன்படுத்தி 3 rows மற்றும் 3 columns கொண்ட
    matrix-ஐ உருவாக்கியுள்ளோம், இதில் எல்லா values-ஐயும் zero-ஆக initialize
    செய்துள்ளோம்.
-   Zeros matrix scientific computing-ல் உள்ள data structures-ஐ initialize
    செய்ய உதவுகிறது, ஏனெனில் calculations-ல் zero values கொண்ட matrix-கள்
    computation-ஐ தொடங்குவதற்கு ஆரம்ப கட்டமாக பயன்படுத்தப்படுகின்றன.

#### எப்போது **matlib.zeros()** பயன்படுத்த வேண்டும்?

-   **Default Initialization**: Numerical operations-ஐ ஆரம்ப கட்டமாக zeros
    matrix-கள் கொண்ட data structure-ஐ பயன்படுத்தும்போது.
-   **Matrix Operations**: Linear algebra மற்றும் matrix multiplication
    போன்ற கணக்கீடுகளுக்கு ஆரம்ப கட்டத்தில் null values ஆக இருக்கும் data-ஐ
    initialize செய்ய வேண்டும்.

#### 18.3. numpy.matlib.ones()

**matlib.ones()** function-ஐ பயன்படுத்தி, எல்லா elements-னும் ones ஆக உள்ள
ஒரு matrix-ஐ உருவாக்கலாம். இது matrix-ஐ முழுமையாக ones values-ஆக
initialize செய்வதற்காக memory-efficient-ஆக செயல்படுகிறது.

**Example:**

``` python
import numpy.matlib as matlib

# Ones matrix உருவாக்கல்
ones_matrix = matlib.ones((2, 4))
print("Ones matrix:\n", ones_matrix)
```

**Output:**

    Ones matrix:
     [[1. 1. 1. 1.]
     [1. 1. 1. 1.]]

#### விளக்கம்:

-   **matlib.ones()** function-ஐ பயன்படுத்தி 2 rows மற்றும் 4 columns கொண்ட
    matrix-ஐ உருவாக்கியுள்ளோம், இதில் எல்லா values-னும் ones ஆக இருக்கும்.
-   இது scientific calculations மற்றும் linear algebra operations-ல்
    முக்கியமான data structures-ஐ initialize செய்ய உதவுகிறது.

#### எப்போது **matlib.ones()** பயன்படுத்த வேண்டும்?

-   **Data Initialization**: Calculations-ஐ ஆரம்பிக்கும் முன் default
    values-ஆக ones கொண்ட data structures-ஐ initialize செய்ய.
-   **Matrix Operations**: Machine learning algorithms மற்றும் matrix
    algebra operations-ல் identity values-ஐ represent செய்ய.

#### 18.4. numpy.matlib.eye()

**matlib.eye()** function-ஐ diagonal values-ல் ones மற்றும் மற்ற இடங்களில்
zeros values கொண்ட ஒரு identity matrix-ஐ உருவாக்க பயன்படுத்தலாம். இது
rectangular shape-உம் diagonal-ல் identity values-ஐ represent செய்யும்.

**Example:**

``` python
# Eye matrix (identity matrix) உருவாக்கல்
eye_matrix = matlib.eye(n=3, M=4, k=0, dtype=int)
print("Eye matrix:\n", eye_matrix)
```

**Output:**

    Eye matrix:
     [[1 0 0 0]
     [0 1 0 0]
     [0 0 1 0]]

#### விளக்கம்:

-   **matlib.eye()** function-ஐ பயன்படுத்தி 3 rows மற்றும் 4 columns கொண்ட
    matrix-ஐ diagonal-ல் ones values-ஐ கொண்டு உருவாக்கியுள்ளோம்.
-   **k=0** என்பது main diagonal-ஐ குறிக்கிறது, ஆனால் positive அல்லது
    negative values கொடுத்தால், upper அல்லது lower diagonals-ஐ represent
    செய்ய முடியும்.

#### எப்போது **matlib.eye()** பயன்படுத்த வேண்டும்?

-   **Identity Matrix Creation**: Linear algebra மற்றும் matrix inversion
    operations-ல் identity matrix-ஐ உருவாக்க.
-   **Diagonal Operations**: Specific diagonal-ல் values-ஐ represent
    செய்து computations-ஐ எளிதாக்க.

#### 18.5. numpy.matlib.identity()

**matlib.identity()** function square matrix-ஐ உருவாக்குவதற்காக diagonal-ல்
மட்டும் ones values-ஐ கொண்டு பயன்படுத்தப்படுகிறது. இது square matrix-களில்
diagonal values-ஐ identity values-ஆக represent செய்யும்.

**Example:**

``` python
# Identity matrix உருவாக்கல்
identity_matrix = matlib.identity(4, dtype=float)
print("Identity matrix:\n", identity_matrix)
```

**Output:**

    Identity matrix:
     [[1. 0. 0. 0.]
     [0. 1. 0. 0.]
     [0. 0. 1. 0.]
     [0. 0. 0. 1.]]

#### விளக்கம்:

-   **matlib.identity()** function-ஐ பயன்படுத்தி 4x4 square identity
    matrix-ஐ diagonal-ல் ones values-ஐ கொண்டு உருவாக்கியுள்ளோம்.
-   Identity matrix என்பது square matrix algebra மற்றும் linear
    transformations-ல் மிகவும் முக்கியமானது.

#### எப்போது **matlib.identity()** பயன்படுத்த வேண்டும்?

-   **Square Matrix Operations**: Linear algebra operations மற்றும்
    machine learning algorithms-ல் identity matrix-ஐ represent செய்ய.
-   **Matrix Calculations**: Square matrix calculations-ஐ ஆரம்ப கட்டத்தில்
    identity values கொண்டு initialize செய்ய.

### 18.6. numpy.matlib.rand()

**matlib.rand()** function-ஐ பயன்படுத்தி, uniform distribution அடிப்படையில்
random values கொண்ட ஒரு matrix-ஐ உருவாக்கலாம். இது scientific computing
மற்றும் statistical analysis-ல் random data generation-ஐ
memory-efficient-ஆக செய்ய உதவுகிறது.

#### Example of Random Matrix Creation

``` python
import numpy.matlib as matlib

# Random matrix உருவாக்கல்
random_matrix = matlib.rand(3, 3)
print("Random matrix:\n", random_matrix)
```

**Output:**

    Random matrix:
     [[0.54358789 0.23467931 0.67890512]
     [0.89012345 0.12345678 0.67894321]
     [0.56781234 0.23456789 0.89123456]]

#### விளக்கம்:

-   **matlib.rand()** function-ஐ பயன்படுத்தி 3 rows மற்றும் 3 columns கொண்ட
    random values கொண்ட matrix-ஐ உருவாக்கியுள்ளோம்.
-   இங்கு random values-ஐ **uniform distribution** அடிப்படையில்
    உருவாக்கியுள்ளோம், அதாவது values-ஐ 0 மற்றும் 1 இடையே சமமான probability
    கொண்டு எடுத்துக்கொள்ளப்பட்டுள்ளன.
-   இந்த method-ஐ stochastic simulations, Monte Carlo methods, மற்றும்
    statistical modeling-ல் random values-ஐ உருவாக்க பயன்படுத்தலாம்.

### எப்போது **matlib.rand()** function-ஐ பயன்படுத்த வேண்டும்?

-   **Statistical Analysis**: Data-ஐ random sampling அடிப்படையில்
    உருவாக்கும்போது.
-   **Simulation Modeling**: Random values-ஐ அடிப்படையாக simulation-களை
    உருவாக்க வேண்டிய data structures-ல்.
-   **Algorithm Testing**: Machine learning algorithms மற்றும்
    computational models-ஐ random input data கொண்டு validate செய்ய.

### Key Features of matlib.rand()

-   **Uniform Distribution**: Random values-ஐ 0 மற்றும் 1 இடையே சமமான
    probability கொண்டு உருவாக்கும்.
-   **Memory-efficient**: Memory-யை அளவிற்கேற்ப allocate செய்து,
    large-scale data generation-ஐ செய்யும்.
-   **Scientific Computing**: Stochastic analysis மற்றும் random sampling
    operations-ஐ memory-efficient-ஆக செய்ய உதவும்.

NumPy-யின் matrix library functions-ஐ memory-efficient-ஆகவும்,
computationally fast-ஆகவும், data structures-ஐ initialize செய்ய
பயன்படுத்தலாம். Scientific computing மற்றும் data analysis-ல் matrix-களை
உருவாக்கவும், manipulate செய்யவும் இந்த functions மிகவும் பயனுள்ளதாக இருக்கும்.