# 2. NUMPY − ARRAY CREATION ROUTINES

Numpy-ல் பல்வேறு array உருவாக்கும் முறைகள் உள்ளன. அவற்றில் சில பொதுவாகப் பயன்படுத்தப்படும் functions பற்றி பார்க்கலாம்.

#### 2.1. numpy.empty

**empty()** function ஒரு initialization values இல்லாத array-ஐ உருவாக்கும்.

In [2]:
import numpy as np

In [4]:
empty_array = np.empty((2, 3))
print("Empty array:\n", empty_array)

Empty array:
 [[4.66651921e-310 0.00000000e+000 2.05833592e-312]
 [6.79038654e-313 2.14321575e-312 2.27053550e-312]]


#### 2.2. numpy.zeros

**zeros( )** function zeros களை கொண்ட array-ஐ உருவாக்கும்.

In [5]:
zeros_array = np.zeros((2, 2))
print("Zeros array:\n", zeros_array)

Zeros array:
 [[0. 0.]
 [0. 0.]]


#### 2.3. numpy.ones

**ones( )** function ones களை கொண்ட array-ஐ உருவாக்கும்.

In [6]:
ones_array = np.ones((3, 3))
print("Ones array:\n", ones_array)

Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
