Numpy-யில் **broadcasting** என்பது shape-கள் வேறுபட்ட array-களை arithmetic operations-ல் பயன்படுத்த ஒரு நுட்பமாகும். இது data-ஐ duplicate செய்யாமல் operations-ஐ நேரடியாக செய்ய உதவுகிறது.

In [5]:
import numpy as np

# Broadcasting உதாரணம்
array1 = np.array([1, 2, 3])
array2 = np.array([[1], [2], [3]])

result = array1 + array2
print("Broadcasted array:\n", result)

Broadcasted array:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


* இங்கு, `array1` மற்றும் `array2`-இன் shape வேறுபட்டிருந்தாலும், broadcasting மூலம் arithmetic operation செய்ய முடிகிறது.